# file types that can be read with the loadData function
# the order specifies preference of types
---
fileTypes:
  - "xlsx"
  - "xls"
  - "odt"
  - "csv"
  - "txt"                       

repositoryMetaFields:
  Repository: "title"
  Name: "name"
  Description: "notes"
  Existing DOI: "ext_doi"
  Assigned DOI: "doi"
  Version: "version"
  Author: "author"
  Author Email: "author_email"
  Maintainer: "maintainer"
  Maintainer Email: "maintainer_email"
  Chronological range (min): "temporal_start"
  Chronological range (max): "temporal_end"
  Spatial Box: "spatial"
